### ISSUE TITLE
{request} Not updated the repository !

### ISSUE THREAD

**Issue by Greyhat890** [synesthesiam/opentts#12]
In DockerHub you have updates the quality of voice and features but when I build it using github docker file  voice quality is poor 
So try to update it

**Comment by synesthesiam** [comment]
I'll check on that this week. I'm hoping to push a new version of OpenTTS with support for some of the SSML standard.

**Comment by synesthesiam** [comment]
Please try OpenTTS 2.1 and see if it's better.
