### ISSUE TITLE
update for Mozilla tts

### ISSUE THREAD

**Issue by erogol** [synesthesiam/opentts#2]
Now Mozilla TTS is a lot faster and it can run on both pytorch and tensorflow. Maybe you can consider to update the interface here to support these new models. Some useful links and examples.

https://colab.research.google.com/drive/1u_16ZzHjKYFn1HNVuA4Qf_i2MMFB9olY?usp=sharing

https://colab.research.google.com/drive/1LgQpdbgLHjyjTxgs6LHaKH_yl0luxkhT?usp=sharing

**Comment by synesthesiam** [comment]
Thanks! I've updated the Docker image and pushed up [the repo for building it](https://github.com/synesthesiam/docker-mozillatts) based on your instructions.
