### ISSUE TITLE
Fast synthesis for speech length estimation

### ISSUE THREAD

**Issue by proudot** [synesthesiam/opentts#21]
Hi, thanks for the great software, 

I was wondering if there is a way to scale down the voice quality (which is very good btw) to accelerate synthesis. I often use opentts to merely estimate the length of a given spoken text, and only need the high quality version. It currently takes quite some time to synthesize a 10 minutes text. Any ideas ? 

Cheers

**Comment by proudot** [comment]
Update for other users,  I just found the low quality option on the web interface, and it is six times faster.

**Comment by synesthesiam** [comment]
FYI for the future: the GlowTTS model alone (without a vocoder) could be used to estimate the length of spoken text much, much faster. In the model's outputs are the predicted durations of each phoneme; simply summing them would give you a good estimate.
