### ISSUE TITLE
Festival breaks on special characters

### ISSUE THREAD

**Issue by alexbarcelo** [synesthesiam/opentts#3]
I was trying the catalan festival voice and it works well except on special characters (like à, é, í, ç...). Same misbehaviour happens also in spanish. Other backends (espeak, nanotts) work correctly with those same characters.

These languages require those special characters. When they appear in a word, the TTS behaves funny and avoids that letter.

Maybe it is related to festival not supporting UTF-8? I just found this link https://www.web3.lu/character-encoding-for-festival-tts-files/ but I know nothing about OpenTTS internals or Festival internals. If that is indeed the case, maybe it is required to do some encoding changing from UTF-8 to ISO-8859-15 for the festival backend? Does that make sense?

**Comment by synesthesiam** [comment]
For future me and others, I've added language-specific encodings here: 449d1a9bcfd17563933eb97681d4db417f0d25b7

Additionally, I'm transliterating Russian since the Festival voice seems to want a Latin script.

**Comment by alexbarcelo** [comment]
In your code you added

>          "ca": "iso-8859-15",  # Not sure if this is correct 

I don't have extensive technical knowledge to back my support, but that is correct (I am a native speaker that has always used that specific encoding and it has always worked well, back in my days of Windows and non-UTF-8, 20-odd years ago).

So `es` and `ca` are properly covered by that. In general, western europe "likes" that encoding. I was checking that for instance German also works well for iso-8859-15 (AFAICT for one letter only, ß, which is present in iso-8859-15 and not present in iso-8859-1). That's not extremely relevant rn because German is not on the list of supported voices, but I am leaving this coment here just in case.

**Comment by synesthesiam** [comment]
I should clarify with the comment that I don't disagree with you, it just contradicts what [the Wikipedia page says](https://en.wikipedia.org/wiki/ISO/IEC_8859). For some reason, both Catalan and Spanish are listed under Part 1.

**Comment by alexbarcelo** [comment]
Mmmm, yeah you are right. I always used ISO-8859-15 growing up because that's what I assume Windows distributions decided to use for all the western european localization, but it is not a necessity for those languages. I stand corrected.

And also my previous comment is mistaken: I saw ß as missing from Part 1, but I really was confusing lowercase and uppercase: ß is indeed in Part 1.

So... Part 15 is correct and you can use it for English, French, Catalan, Spanish, Estonian, Finnish and not look back. There's no "need" to use Part 1. You can decide to use Part 1 for most of those and use Part 15 only for the ones that have special characters not included in Part 1 (Estonian, Finnish, French).

I don't know if there's a benefit on using Part 1, instead of Part 15 for all those. My nostalgia drives me to use Part 15 for everything (including English), but I have no technical motive for doing so.

**Comment by synesthesiam** [comment]
Thanks for your input, I appreciate it. I'll keep Part 15 for Catalan and Spanish. Looks like there's Finnish voice available too; I'll see if I can add that to the Docker image too.

**Comment by synesthesiam** [comment]
By the way, any chance you have some knowledge of how to train a new Festival voice? The docs are quite intimidating, and I'm not sure where to start.
